# NAME: Meiyi Zheng
# EMAIL: meiyizheng@g.ucla.edu
# ID: 605147145


default:
	cp lab3b.py lab3b
	chmod +x lab3b lab3b.py


dist:
	tar -cvzf lab3b-605147145.tar.gz lab3b.py Makefile README


clean:
	rm -rf *.tar.gz lab3b 
