# NAME: Meiyi Zheng
# EMAIL: meiyizheng@g.ucla.edu
# ID: 605147145


default:
	gcc -g lab3a.c -o lab3a  -Wall -Wextra


dist:
	tar -cvzf lab3a-605147145.tar.gz lab3a.c ext2_fs.h Makefile README


clean:
	rm -rf *.tar.gz lab3a *.o
